"""Scaffolding utilities — file generation helpers with traceability headers."""
import os
from datetime import date
from pathlib import Path

from . import config


def make_traceability_header(
    doc_ids: list[str],
    file_ext: str = ".py",
) -> str:
    """Generate a traceability header block for a scaffolded file.

    Args:
        doc_ids: List of source document IDs with versions, e.g. ["HLD-0001 v0.1"]
        file_ext: File extension to determine comment style
    """
    prefix = config.get_comment_prefix(file_ext)
    today = date.today().isoformat()
    source_line = ", ".join(doc_ids)

    if "{}" in prefix:
        # Template-based comment (HTML/XML)
        lines = [
            prefix.format(f"Generated by Narwhal Scaffold Agent"),
            prefix.format(f"Source: {source_line}"),
            prefix.format(f"Generated: {today}"),
            prefix.format(f"DO NOT EDIT — regenerate from /scaffold-* skills"),
        ]
    else:
        lines = [
            f"{prefix} Generated by Narwhal Scaffold Agent",
            f"{prefix} Source: {source_line}",
            f"{prefix} Generated: {today}",
            f"{prefix} DO NOT EDIT — regenerate from /scaffold-* skills",
        ]

    return "\n".join(lines) + "\n"


def ensure_directory(base_dir: str, relative_path: str) -> Path:
    """Ensure a directory exists under the scaffold output tree.

    Returns the absolute path to the directory.
    """
    full_path = Path(base_dir) / relative_path
    full_path.mkdir(parents=True, exist_ok=True)
    return full_path


def list_scaffolded_files(base_dir: str) -> list[str]:
    """List all files in scaffold output directories (src, ci, config, db, tests).

    Returns relative paths from base_dir.
    """
    output_dirs = [
        config.BODY_SRC,
        config.BODY_CI,
        config.BODY_CONFIG,
        config.BODY_DB,
        config.BODY_TESTS,
    ]
    files = []
    for rel_dir in output_dirs:
        abs_dir = Path(base_dir) / rel_dir
        if abs_dir.is_dir():
            for root, _, filenames in os.walk(abs_dir):
                for fname in filenames:
                    full = Path(root) / fname
                    files.append(str(full.relative_to(base_dir)))
    return sorted(files)


def scaffold_status_report(base_dir: str, scaffoldable: list[dict]) -> dict:
    """Generate a status report: scaffolded vs pending.

    Args:
        base_dir: Repository root directory
        scaffoldable: List of knowledge artifacts that can be scaffolded

    Returns dict with:
        scaffolded: list of {doc_type, doc_id, files: [...]}
        pending: list of {doc_type, doc_id, action, output}
        stale: list of {file, source_doc_id, source_version, current_version}
    """
    from . import reader

    existing_files = list_scaffolded_files(base_dir)

    # Parse traceability headers from all existing scaffold files
    file_sources: dict[str, list[dict]] = {}
    for rel_path in existing_files:
        abs_path = str(Path(base_dir) / rel_path)
        sources = reader.parse_traceability_header(abs_path)
        if sources:
            file_sources[rel_path] = sources

    # Build set of doc IDs that have been scaffolded
    scaffolded_ids = set()
    for sources in file_sources.values():
        for s in sources:
            scaffolded_ids.add(s["doc_id"])

    scaffolded = []
    pending = []
    for entry in scaffoldable:
        doc_type = entry.get("doc_type", "")
        doc_id = entry.get("document_id", "")
        info = config.get_scaffold_info(doc_type)
        if not info:
            continue

        if doc_id in scaffolded_ids:
            # Find which files reference this doc
            related_files = [
                fp for fp, srcs in file_sources.items()
                if any(s["doc_id"] == doc_id for s in srcs)
            ]
            scaffolded.append({
                "doc_type": doc_type,
                "doc_id": doc_id,
                "files": related_files,
            })
        else:
            pending.append({
                "doc_type": doc_type,
                "doc_id": doc_id,
                "action": info["action"],
                "output": info["output"],
            })

    # Check for stale files (version mismatch)
    stale = []
    for rel_path, sources in file_sources.items():
        for s in sources:
            # Find current version in knowledge artifacts
            for entry in scaffoldable:
                if entry.get("document_id") == s["doc_id"]:
                    # Extract version from filename
                    import re
                    version_match = re.search(r"_v([\d.]+)\.json", entry.get("relative_path", ""))
                    if version_match:
                        current_ver = version_match.group(1)
                        if s["version"] and s["version"] != current_ver:
                            stale.append({
                                "file": rel_path,
                                "source_doc_id": s["doc_id"],
                                "source_version": s["version"],
                                "current_version": current_ver,
                            })

    return {"scaffolded": scaffolded, "pending": pending, "stale": stale}
